# Generated by Django 3.1.4 on 2021-04-23 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capstonesite', '0003_destination_fav'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination2',
            name='fav',
            field=models.ManyToManyField(related_name='fav_destinations2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='destination3',
            name='fav',
            field=models.ManyToManyField(related_name='fav_destinations3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='destination',
            name='fav',
            field=models.ManyToManyField(related_name='fav_destinations1', to=settings.AUTH_USER_MODEL),
        ),
    ]
