# Generated by Django 3.1.4 on 2021-04-25 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstonesite', '0006_auto_20210424_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepage',
            name='img',
        ),
    ]
