# Generated by Django 3.1.4 on 2021-04-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstonesite', '0005_profilepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepage',
            name='img',
            field=models.ImageField(upload_to='pics2'),
        ),
    ]
