# Generated by Django 3.1.4 on 2021-04-25 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstonesite', '0007_remove_profilepage_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePage',
        ),
    ]
