# Generated by Django 3.1.4 on 2021-04-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('los', models.IntegerField()),
                ('discription', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
